### ISSUE TITLE
default parameters in check_tails wrapper

### ISSUE THREAD

**Issue by smaegol** [LRB-IIMCB/ninetails#1]
Would be great to have default values specified at least for basecall_group, pass_only, num_cores and save_dir in the check_tails function. Those can be easily changed, but with default parameters the running of wrapper will be quicker. 

https://github.com/LRB-IIMCB/ninetails/blob/9a53e2eb5d780c37c06a7930c066ae403390d2d5/R/ninetails_pipeline_wrapper.R#L65

**Comment by nemitheasura** [comment]
Thanks. Updated.
