### ISSUE TITLE
Can Ninetails be applied to R10 data?

### ISSUE THREAD

**Issue by kayla-xu** [LRB-IIMCB/ninetails#12]
If I have R10 data, can I use it? Have you tested how the same data is different on different platforms？

Best,
X.

**Comment by nemitheasura** [comment]
Hi @kayla-xu ,

currently available model is pretrained on R9.4.1 datasets. Since a lot of parameters are changed in the new platform, the results most likely will not be reliable. 

We are working on updating models and on compatibility with pod5. However it would require time. 

Best,
N.
