### ISSUE TITLE
Error: 'convert_tailfindr_output' is not an exported object from 'namespace:ninetails'

### ISSUE THREAD

**Issue by haannguyen** [LRB-IIMCB/ninetails#13]
Hello,

We finally managed to install ninetails! I am trying to load in the tailfindr results, and the convert_tailfindr_output function is erroring out for me with this error: 
`Error: 'convert_tailfindr_output' is not an exported object from 'namespace:ninetails'`

The command I am running is: 
`converted_tailfindr <- ninetails::convert_tailfindr_output(tailfindr_output ='/home/nguyenh/RCS_tail_content_1.csv')`, and I have checked that we have ninetails_1.0.2.

Could you tell me if I am running it incorrectly somehow? Thank you so much!

Yours,
Ha An

**Comment by haannguyen** [comment]
Thank you so much for looking into this! I will ask our server admin to update, and I will try it again soon.

**Comment by nemitheasura** [comment]
Dear @haannguyen,

if your server admin would not want/be able to update, here is the quick workaround:

1. Go to the R subfolder in the ninetails GH repository. 
2. Find the tailfindr_compatibility.R file and open it. 
3. Copy the code of convert_tailfindr_output function. 
4. Paste it into your R/RStudio console (you might also source it in R like this: source("/path/to/tailfindr_compatibility.R")

After that, this function should appear in your environment. Then you should be able to run it in v.1.0.2. In this case, however, you should not provide the ninetails namespace, so your code should look like this:

converted_tailfindr <- convert_tailfindr_output(tailfindr_output = '/path/to/tailfindr/output.csv')

Sorry for this oversight and thank you for pointing out this issue. 

Best,
N. 

P.S.
If you would like to have an immediate assistance, send me an @.
