### ISSUE TITLE
Read nanopolish data from R object not file

### ISSUE THREAD

**Issue by smaegol** [LRB-IIMCB/ninetails#4]
Although it was fixed for the main wrapper, create_outputs() function still tries to read nanopolish data from file even if the R data.frame was provided as the input, throwing an error.

https://github.com/LRB-IIMCB/ninetails/blob/e42b0dc31d7a9e997724dcafe75d483508532544/R/ninetails_data_postprocessing_functions.R#L85

**Comment by nemitheasura** [comment]
Thank you for reporting. Fixed & closed.
