### ISSUE TITLE
error: "Produced feature list is of length 0"

### ISSUE THREAD

**Issue by ana-mil** [LRB-IIMCB/ninetails#6]
Hello, I have tried running the repo on my machine (I should say that my R version is slightly more recent, 4.3.2, but I have installed the repo with no issues). I have tested it with both the repo's test data (with the exact command as in the section "Classification of reads using wrapper function") and on my dataset, but both times I get this error (both times it seems to find the input files): 
  
[2024-02-27 18:02:26.051612] Extracting features of provided reads...                                              
  |==================================================| 100%
Produced feature list is of length 0. Check your input (nanopolish, fast5 files) for integrity.
[2024-02-27 18:02:26.284217] Ninetails aborted.

Do you happen to know what this might be due to? Bellow I attach the whole output I get.

Thanks in advance.

Best,

Ana

-----------------------------------------------------------------------------------------------------
Welcome to Ninetails 1.0.0

[2024-02-27 18:02:25.478036]  Ninetails was launched with following options:
 nanopolish output file:       /home/ana/R/x86_64-pc-linux-gnu-library/4.3/ninetails/extdata/test_data/nanopolish_output.tsv
 sequencing sumary file:       /home/ana/R/x86_64-pc-linux-gnu-library/4.3/ninetails/extdata/test_data/sequencing_summary.txt
 fast5 files directory:        /home/ana/R/x86_64-pc-linux-gnu-library/4.3/ninetails/extdata/test_data/basecalled_fast5
 number of cores:              2
 basecall group:               Basecall_1D_000
 only "PASS" reads included:   TRUE
 output quality control:       TRUE
 output directory:             /home/ana/Projects/NineTails/test_ninetails

[2024-02-27 18:02:25.47882] Pipeline initialized

[2024-02-27 18:02:25.479156] Found 1 fast5 file(s) in provided directory.
[2024-02-27 18:02:25.511588] Analyzing one of the given fast5 files to check
if the data are in required format... 
  Previewed fast5 file parameters:
    data type: RNA 
    fast5 file type: multifast5 
    basecaller used: ONT Guppy basecalling software.  
    basecaller version: 6.0.6+8a98bbcbd  
    basecalling model: flipflop  
  
[2024-02-27 18:02:26.051612] Extracting features of provided reads...                                              
  |==================================================| 100%
Produced feature list is of length 0. Check your input (nanopolish, fast5 files) for integrity.
[2024-02-27 18:02:26.284217] Ninetails aborted.

**Comment by nemitheasura** [comment]
Hi,

sorry for late reply. Please provide me at least with your session info. On the first glance, it might be something wrong with the rhdf5 dependency integration or python/R communication via reticulate. 

Did you install tensorflow?
Did you checked that R recognizes correct python interpreter?
Did you try to use docker instead?

Without further info it would be impossible to debug.

**Comment by nemitheasura** [comment]
Since no further info was provided, I mark this issue as closed for now.
