### ISSUE TITLE
tailfindr compatibility?

### ISSUE THREAD

**Issue by haannguyen** [LRB-IIMCB/ninetails#7]
Hello!

I am working with a short synthetic RNA and looking at the polyA tail by Nanopore sequencing. I am currently using tailfindr to look at the tail length and content. Is there a way to run ninetails with tailfindr instead? 
Or do you have suggestions on if nanopolish can run on an RNA sequence that doesn't align to a reference?

Thank you!

Yours,
Ha An

**Comment by nemitheasura** [comment]
Dear @haannguyen,

thank you for your interest in ninetails. I am working on it. In a matter of days you will be provided with the tailfindR compatibility. 
Just stay tuned!

Best,
Natalia
