### ISSUE TITLE
Installation is too difficult

### ISSUE THREAD

**Issue by jjv5** [LRB-IIMCB/ninetails#9]
It would be very helpful if the entire installation could be gathered into a single place and made with just conda.

The current multistep process of first creating an environment with r-ninetails.yml then adding R and all the required R packages fails on other systems. The version of R needed is buried in a comment in the instructions. It should be included in the conda environment, as well as all required R packages. 

We are unable to install ninetails on our machines (CentOS7, Alma8, Alma9) due to conflicting versions of required packages. 

A single unified installation script would allow many other users to utilize the software.

**Comment by nemitheasura** [comment]
Thank you for giving a try to our software. Currently, as we are working on the revision of our paper, I am unable to provide the conda solution. However, there is a docker, which is a ready-to-use solution. I strongly encourage you to try it. 

For further assistance, @ me. 

Best,
N.

**Comment by jjv5** [comment]
Thanks for the quick reply. I understand the time constraints. Good luck with the paper!

May I suggest removing the conda yml file from the installation docs? It is a bit misleading as it does not produce a working environment for the software. For example, R is missing as well as the many underlying libraries required for R packages (harfbuzz, gdal, fribidi, etc).

**Comment by nemitheasura** [comment]
Thanks, however please keep in mind, that I am unable to test the pipeline on a variety of systems. The recipe in yml file works for multiple distros. Systems used for testing and deployment are listed in the documentation. The same exact yml was used to build environment within the provided docker. The docker was built on rocker/rstudio:4.1.2, all of the required packages are provided in Dockerfile. Nothing is missing. 

Best,
N.
